const Map<String, List<String>> interestsCategoryMap = {
  "Fashion & beauty": [],
  "Outdoors": [
    "Camping",
    "Leisure",
    "Activity",
  ],
  "Arts & culture": [],
  "Animation & comics": [
    "Naruto",
    "One Piece",
    "Blue Rock",
    "Demon Slayer",
  ],
  "Business & finance": [],
  "Food": [],
  "Travel": [
    "Europe",
    "France",
    "Italy",
    "Spain",
    "Swiwss",
    "Country",
    "Airplain",
    "Hotel",
    "Airbnb",
  ],
  "Entertainment": [
    "Anime",
    "Movies & TV",
    "Harry Potter",
    "Marvel Universe",
    "Movie news",
    "Naruto",
    "One Piece",
    "Movies",
    "Grammy Awards",
    "Entertainnment",
    "Guitar Hero",
    "Lier game",
    "Blue Rock",
    "Demon Slayer",
  ],
  "Music": [
    "Rap",
    "R&B & soul",
    "Grammy Awards",
    "Challenge",
    "Vocal",
    "Pop",
    "Rock",
    "К-рор",
    "Music industry",
    "EDM",
    "Jazz",
    "Music news",
    "Hip hop",
    "Reggae",
    "Bebob",
  ],
  "Gaming": [
    "League of Legend",
    "Game Play",
    "Steam",
    "POTG",
    "Roblox",
    "The Finals",
    "Mincraft",
    "Overwatch",
    "PUBG",
    "Heros of the storm",
    "Hearthstone",
    "Starcraft",
    "World of Worcraft",
    "Genshin impact"
  ],
  "Meditation": [],
  "Heeling": [],
  "Gardening": [],
  "Car": [],
  "Special Lunch Set": [
    "WTF",
  ],
};
