name: twitter_clone
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  camera: ^0.11.0+1
  cloud_firestore: ^5.0.2
  cloud_functions: ^5.0.2
  device_preview: ^1.2.0
  faker: ^2.1.0
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  go_router: ^14.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  permission_handler: ^11.3.1
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  video_player: ^2.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
